name: ci

on:
  - push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker build -t build-test .

  integration:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create comment
        id: create
        run: |
          python3 main.py
        env:
          INPUT_TYPE: create
          INPUT_BODY: "- [ ] Run tests"
          INPUT_ISSUE_NUMBER: "1"
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update comment
        id: edit
        run: |
          python3 main.py
        env:
          INPUT_TYPE: edit
          INPUT_BODY: "- [x] Run tests"
          INPUT_COMMENT_ID: "${{ steps.create.outputs.id }}"
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test results
        run: |
          [[ "${{ steps.create.outputs.id }}" == "${{ steps.edit.outputs.id }}" ]] || exit 1
          [[ "${{ steps.edit.outputs.body }}" == "- [x] Run tests" ]] || exit 1
